### ISSUE TITLE
s3control service does not work

### ISSUE THREAD

**Issue by 0xdabbad00** [willbengtson/trailblazer-aws#3]
There is something weird about the new `s3control` service that doesn't work with trailblazer.  I get the following exception:
```
Creating s3control client...
Calling s3control.delete_public_access_block with params {} in us-east-1
Traceback (most recent call last):
  File "cli.py", line 167, in <module>
    cli()
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 98, in cloudtrail_calls
    enumerate_services(ctx.config, services, dry_run=ctx.dry_run)
  File "./trailblazer-aws/trailblazer/enumerate.py", line 94, in enumerate_services
    make_api_call(service, new_func, region, func_params)
  File "./trailblazer-aws/trailblazer/boto/service.py", line 639, in make_api_call

  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "./trailblazer-aws/venv/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3-control.us-east-1.amazonaws.com/v20180820/configuration/publicAccessBlock"
```

That the end-point comes from botocore at https://github.com/boto/botocore/blob/d286246349f7d8e62229fd035e59d7ca1bc297bb/botocore/data/endpoints.json#L1875

**Comment by 0xdabbad00** [comment]
Another weird service is `devicefarm` which is only available in `us-west-2`, so my code recent code updates, which causes trailblazer to only us `us-east-1` causes this service to not be checked.

**Comment by 0xdabbad00** [comment]
Full list of weird services:
```
Skipping discovery - Only available in [u'us-west-2']
Skipping dlm - No regions exist for this service
Skipping eks - No regions exist for this service
Skipping fsx - No regions exist for this service
Skipping globalaccelerator - No regions exist for this service
Skipping iot-jobs-data - No regions exist for this service
Skipping iot1click-devices - No regions exist for this service
Skipping iot1click-projects - No regions exist for this service
Skipping kafka - No regions exist for this service
Skipping license-manager - No regions exist for this service
Skipping macie - No regions exist for this service
Skipping mediaconnect - No regions exist for this service
Skipping mgh - Only available in [u'us-west-2']
Skipping mobile - No regions exist for this service
Skipping mq - No regions exist for this service
Skipping pi - No regions exist for this service
Skipping quicksight - No regions exist for this service
Skipping ram - No regions exist for this service
Skipping rds-data - No regions exist for this service
Skipping robomaker - No regions exist for this service
Skipping route53resolver - No regions exist for this service
Skipping securityhub - No regions exist for this service
Skipping signer - No regions exist for this service
Skipping sms-voice - No regions exist for this service
Skipping transcribe - No regions exist for this service
```

For the ones where no regions exist, you must need to sign up for a beta I'm guessing.
